<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/02/17 19:24:42

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=symfony1_4',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
